spring.application.name=reporte
# API Key de LocationIQ
locationiq.api-key=pk.2e92838d440f2603cc598bce80e25847

server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5432/sanosysalvos_db
spring.datasource.username=postgres
spring.datasource.password=sanosysalvos



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


logging.level.root=INFO
logging.level.cl.sanosysalvos.reporte=DEBUG